### ISSUE TITLE
Corde recognize files as empty

### ISSUE THREAD

**Issue by Rapougnac** [cordejs/corde#1109]
**Describe the bug**
Corde think the test file is empty

**To Reproduce**
Follow the steps described in [cordejs docs](https://cordejs.org/docs/) -> Getting Started

**Expected behavior**
Corde supposed to test my code

**Screenshots**:
![corde schema json - I_Like_Rain - Visual Studio Code  Unsupported  06 11 2021 22_13_54](https://user-images.githubusercontent.com/74512338/140623966-2e019b9e-c5d4-407f-a498-aa5d31f83376.png)

**Desktop:**

- OS: Windows_NT 
- Terminal: Powershell
- Corde version: 4.4.4

**Additionnals informations**:
I installed corde with pnpm

**Comment by lucasgmagalhaes** [comment]
Hi @Rapougnac, thank you for reporting this issue. Can you provide a repo so I can reproduce the bug?

**Comment by Rapougnac** [comment]
> Hi @Rapougnac, thank you for reporting this issue. Can you provide a repo so I can reproduce the bug?

Sure ! Here it is <https://github.com/Rapougnac/Kiwiibot-typescript>. I tested with discord.js v12 & v13. I also noticed that in v13 an error is thrown.

**Comment by lucasgmagalhaes** [comment]
@Rapougnac  I had to disable a lot of things to be able to fully run corde. But I could not reproduce the error. I'm using node 17.0.1, and Windows 11 but all I could get was

![image](https://user-images.githubusercontent.com/19666463/140830041-4dc698a8-fd74-4201-8bc8-665e9ae2638a.png)

or 

![image](https://user-images.githubusercontent.com/19666463/140830095-9977fd5a-a21f-42d4-934f-45235689edaa.png)

And  about this

```
I also noticed that in v13 an error is thrown.
```

Yeah, corde will throw some errors when using discord.js v13, because it hasn't support for it yet :(

**Comment by lucasgmagalhaes** [comment]
@Rapougnac, I found the problem. When you import corde's functions locally, and runs corde globally. The global corde do not finds the tests added in local import. So, you need to run corde locally (yarn corde or npm run corde).

Sorry about that. To avoid other errors like that, I gonna remove global install documentation from "Getting started" and add corde's function to node's global.

As about v13 of discord.js. Corde do not support this version yet.

**Comment by Rapougnac** [comment]
Yup, seems better than before, but now, I'm facing a new issue 😓. Corde continuously says "login to corde bot". 
I ran `npx corde`, `yarn corde` & `pnpx corde`, but the result is always the same.
I didn't edited my corde.config.json file.

**Comment by lucasgmagalhaes** [comment]
When you say that you didn't edit your corde.config, you are telling that you just generated it and ran `yarn corde`? All required properties are filled?

I also noticed this in [index.test.js](https://github.com/Rapougnac/Kiwiibot-typescript/blob/main/tests/index.test.js):

```js
beforeStart(() => {
    client.connect();
    client.start();
});
```

`client.connect()` is a async function. So you should do this:

```js
beforeStart(async () => {
    await client.connect();
    client.start();
});
```

**Comment by Rapougnac** [comment]
> When you say that you didn't edit your corde.config, you are telling that you just generated it and ran yarn corde? All required properties are filled?
Sorry for the misunderstanding ^^" 
I had already filled in the properties beforehand, but what I meant was that I didn't modify the tokens, ids, etc. 

And about the
```ts
client.connect();
```
method, it's isn't asynchrounous. I defined [here](https://github.com/Rapougnac/Kiwiibot-typescript/blob/fae541519979000316cfd148023fbad0a27795cb/src/struct/Client.ts#L136). I just added the public keyword, but not async

**Comment by lucasgmagalhaes** [comment]
the `login` function of Discord.js client does is async. [Client](https://github.com/discordjs/discord.js/blob/main/typings/index.d.ts#L529)

```js
Client.login(token?: string): Promise<string>
```

The point is that you are not waiting for it in your declaration. It should be like this:

```js
    public async connect(token: string | undefined = this.config.discord.token): Promise<this> {
        // Log super in with the supplied token
        await super.login(token).catch(console.error);
        return this;
    }
```

**Comment by Rapougnac** [comment]
Ahh, yeah, that's right, sorry for this mistake, I fixed this, but it still not working, I don't know why

**Comment by Rapougnac** [comment]
Okay, so I changed my computer, and I created

**Comment by Rapougnac** [comment]
Sorry I missclicked, didn't mean to close this issue

**Comment by lucasgmagalhaes** [comment]
@Rapougnac, try to await every async function that is called inside corde's `beforeStart` function. I noticed that `client.start();` is also an async function.

[start](https://github.com/Rapougnac/Kiwiibot-typescript/blob/fd2282be26b13b114a50e7c26dabe5f9e82e5cc8/src/struct/Client.ts#L244)
```js
    public start() {
        //Load the events, player events and commands
        this.loadEvents().loadCommands();

        //Mongodb
        if (this.config.database.enable) {
            this.mongoInit(); // This is async
        } else {
            mongoose.disconnect();
            Console.warn(
                'Database is not enabled! Some commands may cause dysfunctions, please active it in the config.json!'
            );
        }
        return this;
    }
```
[mongoInit](https://github.com/Rapougnac/Kiwiibot-typescript/blob/fd2282be26b13b114a50e7c26dabe5f9e82e5cc8/src/struct/Client.ts#L244)
```js
    public mongoInit() {
        mongoose
            .connect(this.config.database.URI, this.config.database.config)
            .then(() => {
                Console.success(`Connected to MongoDB`, 'MongoDB');
            })
            .catch((e) => {
                Console.error('Failed to connect to MongoDB', e);
            });
    }
```

Try using `await` so we can check if corde well then work.
Also, really sorry for the delay in some response. I hadn't time to work in the lib :(

**Comment by Rapougnac** [comment]
Thanks, I'll try this asap, but I don't have a lot of time too
> Also, really sorry for the delay in some response. I hadn't time to work in the lib :(

No problem, take your time, I'm not in a hurry ❤

**Comment by Rapougnac** [comment]
So. I tried, but still the same result 😓
Can I fork your repo and try to find where the issue comes from ?

**Comment by lucasgmagalhaes** [comment]
😓, of course!

**Comment by Rapougnac** [comment]
Okay, so, I found what's the cause of the issue, but I don't know how to fix it.
> the token is unavaliable to the client.

This error is thrown because the ready event is not triggered, so the client is uninitialized and cannot access to all of it's properties.
The main problem now, is that the `group`, `test`, `expect` and `toReturn` are fired before the trigger of the ready event, and the client is still missing properties. And I don't really know how to wait for the client to be ready 😓

**Comment by lucasgmagalhaes** [comment]
The ready event is not being triggered by your bot? If so, you can implement your **connect** function to handle it, like:

```js
async function login() {
  const readyPromise = new Promise((resolve) => {
    bot.once("ready", () => {
      resolve();
    });
  });
  await bot.login(config.botToken);
  await readyPromise;
}
```

**Comment by Rapougnac** [comment]
Hello! Sorry for the late reply, I am really busy theses days, thanks for your response, I try this as soon as possible ^^

**Comment by Rapougnac** [comment]
Okay, so, I tried with your technique, and finally, it seems to work, tysm for your help ❤.
And, keep it up :D! You're doing an amazing work
