### ISSUE TITLE
[Question] Why is the (main) bot token required?

### ISSUE THREAD

**Issue by HeCorr** [cordejs/corde#1185]
I was wondering.. Why do you require the `botToken` to be supplied in the config if in the getting started example you execute `loginBot()` which handles the main bot's token internally?

I really don't believe Corde needs to have access to the main bot's token, only the secondary/test bot's token.

**Comment by HeCorr** [comment]
I just tested it, and it seems to work perfectly fine no matter what I set the token to in the config.

I'm really not sure why you would ask for the token and even make it required.

**Comment by lucasgmagalhaes** [comment]
Hi @HeCorr!. It was my mistake. Actually, corde doesn't need `botToken` . I think that it was needed in an old version, but isn't today. I gonna try to release a version today removing it. Thank you for the appointment and sorry for that!

**Comment by HeCorr** [comment]
That makes sense. Thank you!

**Comment by AxeAlasmar2022** [comment]
هل هنا برمجي يقدر يفيدني بامور متعلقه في بوت ديسكورد
