### ISSUE TITLE
node:events not found

### ISSUE THREAD

**Issue by lucasgmagalhaes** [cordejs/corde#1249]
![image](https://user-images.githubusercontent.com/19666463/156425846-92d1123c-cca5-4372-aa18-4540cd34a9af.png)

**Comment by lucasgmagalhaes** [comment]
Error caused by [esm](https://www.npmjs.com/package/esm)

**Comment by ErlanBazarov** [comment]
@lucasgmagalhaes  Having the same issue. Can you explain how to solve this?

**Comment by lucasgmagalhaes** [comment]
Hi @ErlanBazarov! The issue was caused by the esm library.

![image](https://user-images.githubusercontent.com/19666463/162198348-33754e21-2564-44b5-9ec9-9ed62cb52120.png)

I just remove it and it started to work again!
