### ISSUE TITLE
Is it possible to use corde in combination with jest?

### ISSUE THREAD

**Issue by ErlanBazarov** [cordejs/corde#1317]
I would like to run tests using corde in combination with jest. Is it possible? For example:
```
group('test groups', () => {
  beforeEach(() => {
    console.log("I'll back")
  })

  test('test 1', () => {
    expect('hi').toEqual('hi') // jest's assertion
    expect('hi').toReturn('hello') // corde's assertion
  })
})
```
After running `npx corde`. It returns:
```
Test Files: 1 empty. 1 total
Tests:      0 total
Time:       4ms
```

**Comment by lucasgmagalhaes** [comment]
Hi @ErlanBazarov. Unfortunately, for now, corde has no integration with Jest. But in the next [version (5.0)](https://github.com/cordejs/corde/pull/1024), it will have its own unity testing library ([types declaration here](https://github.com/cordejs/corde/blob/expect/src/global/expect.d.ts)). The syntax will be the same as Jest. and bot tests will be renamed to `command` as you can see [here](https://github.com/cordejs/corde/blob/expect/src/global/command.d.ts)

**Comment by lucasgmagalhaes** [comment]
I'm going to close the issue. If there's anything else, feel free to reopen this issue or open another one
