### ISSUE TITLE
CordeJS overrides my discord client 

### ISSUE THREAD

**Issue by Srivastava57Harsh** [cordejs/corde#1521]
**Describe the bug**

**To Reproduce**

**Link repo with the error**

A repo to reproduce the error with instructions for how to
set things ready to start testing.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Terminal [e.g PowerShel, cmd, GitBash]
- Corde version [e.g. 22]

**Additional context**

**Comment by Srivastava57Harsh** [comment]
hey @lucasgmagalhaes as per our conversation I have created an issue :)

**Comment by lucasgmagalhaes** [comment]
Hi @Srivastava57Harsh. could you provide more details about your problem? What is being overrided?

**Comment by lucasgmagalhaes** [comment]
As you informed me that you fixed your problem in Linkedin, I going to close this issue. Feel free to reopen in any case :)
