### ISSUE TITLE
Cannot find test

### ISSUE THREAD

**Issue by kaaax0815** [cordejs/corde#713]
**Describe the bug**
If i run corde it says it cannot find my test

**To Reproduce**
No Steps, I basically copied the example

**Expected behavior**
Just run the test

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10 20H1
- Terminal [e.g PowerShel, cmd, GitBash] Powershell or GitBash
- Corde version [e.g. 22] 4.0.2

**Additional context**
Github Repo: https://github.com/kaaaxcreators/Discord-MusicBot/tree/test
I created my Bot through Typescript, but I import the Compiled Javascript Version.
But this shouldnt matter because it doesnt even go to test, it fails after logging in

test/bot.test.js:
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const { group, test, command, beforeStart, afterAll, expect } = require('corde');
// You can also import const corde = require("corde"); This is a default export with all others
// functions.
const { client } = require('../dist/index');

beforeStart(() => {
  client.login(process.ENV.TOKEN);
});

group('main commands', () => {
  test("hello command should return 'Hello!!'", () => {
    expect('hello').toReturn('Hello!!');
  });
});

afterAll(() => {
  client.destroy();
});
```

corde.config.js
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const dotenv = require('dotenv-safe');
dotenv.config();

module.exports = {
  cordeBotToken: process.env.CORDETOKEN || 'cordeBotToken',
  botTestId: process.env.BOTID || 'botTestId',
  botToken: process.env.TOKEN || 'botToken',
  guildId: process.env.GUILDID || 'guildId',
  channelId: process.env.CHANNELID || 'channelId',
  botPrefix: 'm',
  testMatches: ['./test']
};
```

**Comment by lucasgmagalhaes** [comment]
Hi, @kaaax0815. Sorry about that. I already identified the root of the problem. I'm using a pattern match to read test files, so in the next release to get all tests for `./test` folder, please change your configs to `./test/**`

**Comment by kaaax0815** [comment]
Hi, @lucasgmagalhaes. It stills throws the Error, but runs anyway

**Comment by kaaax0815** [comment]
I have a different error now. I want to expect an error but MessageEmbed is not assignable to IMessageEmbed

**Comment by lucasgmagalhaes** [comment]
@kaaax0815 try version 4.0.3

**Comment by kaaax0815** [comment]
@lucasgmagalhaes Fixed the Error
