### ISSUE TITLE
Make Color of Embed Optional

### ISSUE THREAD

**Issue by kaaax0815** [cordejs/corde#722]
**Is your feature request related to a problem? Please describe.**
I want to test the Bot if it returns the right message. but if dont set the color it fails

**Describe the solution you'd like**
Make color optional

**Describe alternatives you've considered**
`RANDOM` doesnt work unfortunately

**Additional context**
https://github.com/cordejs/corde/discussions/721

**Comment by lucasgmagalhaes** [comment]
Hi @kaaax0815 just to be aware, I'm working on a test function to solve your problem. Still this week I will release a version with this function for you

**Comment by lucasgmagalhaes** [comment]
Hi, @kaaax0815. I just released version 4.1.0. It contains a function called `toEmbedMatch`. This function checks partially a embed message, So if you do not pass the property color, your tests will woks.

**Comment by kaaax0815** [comment]
@lucasgmagalhaes thanks I'll check it out asap
