### ISSUE TITLE
corde thinks file is empty

### ISSUE THREAD

**Issue by a1cd** [cordejs/corde#785]
**Describe the bug**
corde thinks file is empty

**To Reproduce**

download this:
[code](https://github.com/a1cd/Discord-Commands/tree/c544d67b20d110c4ff1b09207e3ff00c0325a632)
and run `corde`

**Expected behavior**

**Screenshots**
<img width="1129" alt="Screen Shot 2021-06-17 at 7 45 59 PM" src="https://user-images.githubusercontent.com/71281043/122485354-a7b25300-cfa4-11eb-99e8-b7ee542dd785.png">

**Desktop (please complete the following information):**

- OS: macOS
- Terminal vsCode
- Corde version v4.1.2

**Additional context**

**Comment by lucasgmagalhaes** [comment]
Weird. Did you already tried to set `testMatches` as ["./src/tests/**"]? It's just a attempt, but I will check this out

**Comment by a1cd** [comment]
Yep

**Comment by lucasgmagalhaes** [comment]
@a1cd, you forgot to import `expect` from "corde"

**Comment by a1cd** [comment]
ty, ill have to check if this fixes it later

**Comment by lucasgmagalhaes** [comment]
As this issue had no update, I going to close it. Feel free to reopen with some comments :)
