### ISSUE TITLE
toReturn recognize image

### ISSUE THREAD

**Issue by vinamarie8** [cordejs/corde#793]
**Is your feature request related to a problem? Please describe.**
My bot replies with a singular image according to certain commands.

**Describe the solution you'd like**
I would like the toReturn function to be able to recognize an image or file argument.

**Describe alternatives you've considered**
A general parameter for toReturn that can compare expected result with any singular node of the message object.

**Additional context**
I am not using messageEmbed for this reply, only message.

**Comment by lucasgmagalhaes** [comment]
Hi @vinamarie8, just for me to understand. You are expecting to receive something like `"../img/image.png` and in the sent message the image URL is something like `https://cdn.discordapp.com/attachments/...."`?

**Comment by lucasgmagalhaes** [comment]
As this issue had no update, I going to close it. Feel free to reopen with some comments :)
